# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f62bc4e2ba18f449cde0319be89e3f84558b3c0df6a0ce9a86179e58d339e1acc749d575b470dddbd5b66dc8eddf48a1a941938b6f11c967afb83f01ff31da15

test:
  secret_key_base: 2c1609d615420aed503564d9451b172727e467bd9f8267a4220b0dbf69080ce9a6db80a652a7528fab7d2f95540b2e15b1dc129c43b0e84158868f7dda541b6a

production:
  secret_key_base: 40dd670e2da3f628d47f44b0e83a7cf29098fbac5fbea8206f20e40174b1cbb83ca3345322c495e2348ebbaa231eb8a717df97980158cc91b351e7ab3a65c32c
